### ISSUE TITLE
Cloze deletion can only be used in fields which use the cloze filter. this is typically the first field

### ISSUE THREAD

**Issue by Pachendale** [saiyr/cloze-overlapper#1]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

I made 5 overlapping cards, when I attempted to make a sixth I could not use the add a deletion button in the first, Original Field keep getting errors:
"Cloze deletion can only be used in fields which use the cloze filter. this is typically the first field"

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: Windows 11
- version:23H2

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

ankiconnect
basic printing support
cloze overlapper for 23x
image occlusion enhanced

#### Error message (if any)

Cloze deletion can only be used in fields which use the cloze filter. this is typically the first field

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by saiyr** [comment]
Sorry for the delay. I didn't receive a notification. Are you sure you used the right button? There are two, one has the caption "Cloze deletion (new card)" and another has "Overlapping cloze deletion". It's the second one you need. If it generates curly braces instead of square brackets, you're using the wrong button.

**Comment by Pachendale** [comment]
Hey, sorry I thought I had closed the ticket out, yes , I figured out that I was doing it wrong. Thanks for getting back to me.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by saiyr** [comment]
Excellent. Glad you figured it out.
